### PR TITLE
Generate stable Scope IDs

### PR DESCRIPTION
**Pull request by crisptrutski**
Refs https://github.com/metabase/macaw/issues/66

Not closing it on merge as we may want smarter "invalidation" behavior.

### CODE REVIEW

**Comment by crisptrutski** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/metabase/macaw/67?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#67** <a href="https://app.graphite.dev/github/pr/metabase/macaw/67?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#65** <a href="https://app.graphite.dev/github/pr/metabase/macaw/65?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#64** <a href="https://app.graphite.dev/github/pr/metabase/macaw/64?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#61** <a href="https://app.graphite.dev/github/pr/metabase/macaw/61?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#60** <a href="https://app.graphite.dev/github/pr/metabase/macaw/60?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#56** <a href="https://app.graphite.dev/github/pr/metabase/macaw/56?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#54** <a href="https://app.graphite.dev/github/pr/metabase/macaw/54?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @crisptrutski and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by piranha — APPROVED** [review]
Ehm... I wonder if some map shape like `{:id 3 :smth "SELECT"}` would be better? Maybe not though, as we'll have them like a path in the end, right?

**Comment by crisptrutski** [comment]
> Ehm... I wonder if some map shape like `{:id 3 :smth "SELECT"}` would be better? Maybe not though, as we'll have them like a path in the end, right?

For me the end game is might be to return the top-most id, instead of a vector of scopes. We can then then use those ids to look stuff up in a big scopes map? I'm not likely how memory intensive this is.

**Comment by crisptrutski** [comment]
Thinking out loud, we'd have stuff like:

```clojure
;; columns - replaces our flat one
{scope-id-1 #{{:table "a" :column "x" :alias "y"} ...}
 scope-id-2 #{{:table "a" :column "x" :alias "z"} ...}}

;; contexts
{scope-id-1 ["SELECT"]
 scope-id-2 ["SUBSELECT" "SELECT"]}
```

**Comment by crisptrutski** [comment]
### Merge activity

* **Jun 21, 7:59 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/metabase/macaw/67) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
